import React from 'react';

export const Select = React.forwardRef<HTMLSelectElement, React.SelectHTMLAttributes<HTMLSelectElement>>(
  (props, ref) => <select ref={ref} {...props} />
);

Select.displayName = "Select";

// Remove these components as they're causing the object rendering error
// export const SelectTrigger = ...
// export const SelectContent = ...
// export const SelectItem = ...
// export const SelectValue = ... 